### ISSUE TITLE
Contando nos internos 

### ISSUE THREAD

**Issue by thiago-cipitelli** [sulyak/EstruturaDeDados#1]
a função de contar nós internos esta errada.
se !a->esq e !a->dir, entao deve retornar 1

**Comment by sulyak** [comment]
ok boomer.

se !a->esq e !a->dir, entao ele eh um no folha, nao? no folha == sem filhos

se ele eh um no folha, entao ele n eh um no interno, logo retorna 0

**Comment by sulyak** [comment]
closed

alce meter: 🔥🔥🔥🔥

**Comment by sulyak** [comment]
closed

alce-meter: 🔥🔥🔥🔥🔥
